apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: source
spec:
  type: git
  params:
    - name: gitrevision
      value: master
    - name: gitrepositoryurl
      value: https://github.com/donaldscottthesecond/tekton-argocd-code-sq3